### ISSUE TITLE
Stopped working with 0.115.0

### ISSUE THREAD

**Issue by thomasgregg** [msp1974/homeassistant-jlrincontrol#48]
![image](https://user-images.githubusercontent.com/2538782/93515279-a0ccb600-f928-11ea-90a1-6c7ed6db4d48.png)

![image](https://user-images.githubusercontent.com/2538782/93515366-c3f76580-f928-11ea-95d6-74b4c38adb19.png)

`Logger: homeassistant.setup
Source: setup.py:280
First occurred: 8:56:38 PM (1 occurrences)
Last logged: 8:56:38 PM

Unable to prepare setup for platform jlrincontrol.sensor: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).`

**Comment by msp1974** [comment]
Updated version released v2.1.2 to fix change in HA constant name in v0.115.0.

Can you let me know if fixed once updated. Thx

**Comment by thomasgregg** [comment]
Fixed. Thanks a lot.
