### ISSUE TITLE
Battery charge sensor has invalid value in 3.0.0 beta 1

### ISSUE THREAD

**Issue by Djelibeybi** [msp1974/homeassistant-jlrincontrol#114]
Just got this error after upgrading to v3.0.0 beta 1:

```log
2024-02-02 04:00:26.981 INFO (MainThread) [custom_components.jlrincontrol] Unloading JLR InControl Component
2024-02-02 04:00:26.996 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'batteryVoltage' when rendering '{{ state_attr('sensor.discovery_sport_all_info','core status').batteryVoltage }}'
2024-02-02 04:00:26.996 ERROR (MainThread) [homeassistant.helpers.event] Error while dispatching event for sensor.discovery_sport_all_info to <Job track state_changed event {'sensor.discovery_sport_all_info'} HassJobType.Callback <bound method TrackTemplateResultInfo._refresh of <TrackTemplateResultInfo {Template<template=({{ state_attr('sensor.discovery_sport_all_info','core status').batteryVoltage }}) renders=8>: <RenderInfo Template<template=({{ state_attr('sensor.discovery_sport_all_info','core status').batteryVoltage }}) renders=8> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.discovery_sport_all_info'}) rate_limit=None has_time=False exception=None is_static=False>}>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 639, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 642, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 296, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 691, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1215, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 691, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 429, in _handle_results
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 646, in state
    raise ValueError(
ValueError: Sensor sensor.discovery_sport_battery_voltage has device class 'voltage', state class 'measurement' unit 'V' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '' (<class 'str'>)
2024-02-02 04:00:27.013 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'tuStatusPrimaryChargePercent' when rendering '{{ state_attr('sensor.discovery_sport_all_info','core status').tuStatusPrimaryChargePercent }}'
2024-02-02 04:00:27.013 ERROR (MainThread) [homeassistant.helpers.event] Error while dispatching event for sensor.discovery_sport_all_info to <Job track state_changed event {'sensor.discovery_sport_all_info'} HassJobType.Callback <bound method TrackTemplateResultInfo._refresh of <TrackTemplateResultInfo {Template<template=({{ state_attr('sensor.discovery_sport_all_info','core status').tuStatusPrimaryChargePercent }}) renders=8>: <RenderInfo Template<template=({{ state_attr('sensor.discovery_sport_all_info','core status').tuStatusPrimaryChargePercent }}) renders=8> all_states=False all_states_lifecycle=False domains=frozenset() domains_lifecycle=frozenset() entities=frozenset({'sensor.discovery_sport_all_info'}) rate_limit=None has_time=False exception=None is_static=False>}>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 639, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 642, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 296, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 691, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1215, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 691, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 429, in _handle_results
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 646, in state
    raise ValueError(
ValueError: Sensor sensor.discovery_sport_battery_charge has device class 'battery', state class 'measurement' unit '%' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '' (<class 'str'>)****
```

**Comment by msp1974** [comment]
Can you provide diagnostic download. Thx

**Comment by Djelibeybi** [comment]
Sure. Here you go.

[config_entry-jlrincontrol-f9956c9594093151c8e7d18c2f427721.json.txt.json](https://github.com/msp1974/homeassistant-jlrincontrol/files/14128837/config_entry-jlrincontrol-f9956c9594093151c8e7d18c2f427721.json.txt.json)

**Comment by msp1974** [comment]
Great thx.  So I think this is a template sensor you have created that errored when the integration was unloaded.  Does this template sensor work with v3.0.0beta1 after you installed it?  If not, what is the yaml of the template sensor?

**Comment by Djelibeybi** [comment]
I was about to reply that I don't have any template sensors but thought I should double-check just to be sure. Turns out I had two sensors configured via the Helpers screen and I don't even remember creating them. Deleting them has resolved the issue.
